name: Build LaTeX document
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_latex"
  build_latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile Resume
        uses: dante-ev/latex-action@latest
        with:
          root_file: 'resume.tex'
    
