# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_latex"
  build_latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile Resume
        uses: vinay0410/tectonic-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tex_path: 'resume.tex'
          push: 'yes'
      - name: Compile CV
        uses: vinay0410/tectonic-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tex_path: 'CV.tex'
          tex_path: 'cv.tex'
          push: 'yes'
